name: Test PR

on: [pull_request]

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run lint
      - run: echo "STORAGE_ID=${{ secrets.STORAGE_ID }}\nSTORAGE_REGION=${{ secrets.STORAGE_REGION }}\nSTORAGE_SECRET=${{ secrets.STORAGE_SECRET }}" >> .env
      - run: npm run test
      - run: npm run build
